### ISSUE TITLE
dropdown-menu position

### ISSUE THREAD

**Issue by sunlightsuraj** [timcreative/material-kit#21]
I want the dropdown menu to open on left side. When I add .dropdown-menu-left or .pull-left class to the .dropdown-menu, happen nothing.

**Comment by alexandru-paduraru** [comment]
@sunlightsuraj I've added the class "dropdown-menu-left" instead of "dropdown-menu-right" and the dropdown is moving to the left side without any problems. Please check this image:

<img width="481" alt="screen shot 2016-07-01 at 18 29 05" src="https://cloud.githubusercontent.com/assets/2517758/16526403/cd185750-3fb9-11e6-913b-2090ccf138eb.png">

Can you give us more details?

Best,
Alex

**Comment by sunlightsuraj** [comment]
Ok its working now, Thanks
