### ISSUE TITLE
less files?

### ISSUE THREAD

**Issue by krebbi** [timcreative/material-kit#33]
could you please include the less-files also into your repo?

**Comment by alexandru-paduraru** [comment]
@krebbi thank you for using our product. We've built Material Kit over our Friend Federico's: http://fezvrasta.github.io/bootstrap-material-design/ and we've been working only with SASS files and not the LESS (most of our products are on SASS and Bootstrap 4 will migrate from LESS to SASS). There are some files who have the "this files was generated with less etc" because it was there from the original repo. We have to delete that text because it is confusing and it's not valid anymore.

Hope you understand the situation.

Best,
Alex

**Comment by krebbi** [comment]
thx for your answer, because of this text i asked. ;)
