### ISSUE TITLE
Dropdown Menu Stay Selected

### ISSUE THREAD

**Issue by cernst33** [timcreative/material-kit#38]
Is there a way for the dropdown list to stay on the selected item? currently the selection does not stay, or the page posts back.

**Comment by alexandru-paduraru** [comment]
Yes, you should add via Javascript or when you open a new page the class "active" to the parent of the link, something like this:

``` <li class="active">
            <a href="link_to_your_page">Your Page</a>
       <li>
```

The Page posts back now because there are "#" as the links from the ```a tags```. This will not be a real case when you will add real links there.

Please let me know if that was working fine.

Best,
Alex
