### ISSUE TITLE
Meteor Project

### ISSUE THREAD

**Issue by i-siddiq** [timcreative/material-kit#42]
I am trying to use material kit pro in my meteor project, I have tried adding the assets folder in client/lib folder but the libraries are not loaded like this, could you please give some indicators how to use the kit in a meteor projects.

**Comment by alexandru-paduraru** [comment]
Hi @i-siddiq! Thank you for using our product. Unfortunately we don't have experience with meteor. We've found some tutorials on how to integrate a Bootstrap Theme/Kit with meteor here:

1. https://www.youtube.com/watch?v=4grO6Cnp6t4&list=PLDefGXnfIlHlSeRNxl-lxAYJakUSDRVgE&index=2
2. http://www.manuel-schoebel.com/blog/meteorjs-and-twitter-bootstrap---the-right-way

Please let us know if that was useful, otherwise, you can tell us which is the structure of Meteor folders and how the assets pipeline is working and we will try to give you a solution. You can also send us a link to your application to see on the live example what is wrong.

Best,
Alex

**Comment by i-siddiq** [comment]
Ok I was able to integrate the package in meteor. I made a local package with all required js and css files. Do not include jQuery in this package , that messes up stuff. add jQuery by the following command in app directory:
>meteor npm install jquery
This will install jquery in /app/node_modules/jquery.
Since I am using pro version I could not make the package public.

**Comment by alexandru-paduraru** [comment]
@i-siddiq that's great! Happy to know that you've got the solution. If you think the Material Kit will be a good package for Meteor, would you like to make it for the Free Version? We would be happy to add you as our collaborator.

Best,
Alex

**Comment by i-siddiq** [comment]
@alexandru-paduraru  sorry read your message very late, I will do that for the free version, I believe  its a good package for meteor. I will let you know when I am done.

**Comment by alexandru-paduraru** [comment]
@i-siddiq No worries, please let us know if you need any help. I'm 100% that the users from Creative Tim will love it! Keep in touch!

**Comment by mullojo** [comment]
Hi @alexandru-paduraru, I just purchased Material Kit Pro and I'm also having a hard time figuring out how to get the package to load in Meteor.  I'm unsure on what package dependancies might be required in Meteor.  If you could give a quick summary of what your project directory looks like or what you removed from the HTML files to work with Meteor, that would be a big help!

**Comment by mullojo** [comment]
@alexandru-paduraru, instead of trying to figure out how Material Kit Pro should be used with Meteor, maybe it is just easier to explain the dependancies in Material Kit Pro.  To me it looks like each HTML references what it needs in the assets, but I'm trying to pick one simple page from your templates and figure out which assets it depends on 👍

**Comment by alexandru-paduraru** [comment]
@mullojo thank you for using our product. As we said in the previous comments, unfortunately we don't have experience with Meteor :-( we added 2 links there with some tutorials.

Now for our product the dependencies are like this:

**Design**

```html
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

<!-- CSS Files -->
<link href="../assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="../assets/css/material-kit.css" rel="stylesheet"/>
```

**Javascript**

```html
<!--   Core JS Files. You need to include all these 3 on all the pages   -->
	<script src="../assets/js/jquery.min.js" type="text/javascript"></script>
	<script src="../assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../assets/js/material.min.js"></script>

<!-- Here comes the extra plugins for different elements like datepickers, sliders, tags, file uploader etc. You can choose only the one that you want -->

	<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
	<script src="assets/js/moment.min.js"></script>

	<!--	Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src="../assets/js/nouislider.min.js" type="text/javascript"></script>

	<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
	<script src="../assets/js/bootstrap-datetimepicker.js" type="text/javascript"></script>

	<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
	<script src="../assets/js/jquery.select-bootstrap.js" type="text/javascript"></script>

	<!--	Plugin for Tags, full documentation here: http://xoxco.com/projects/code/tagsinput/  -->
	<script src="../assets/js/jquery.tagsinput.js"></script>

	<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
	<script src="../assets/js/jasny-bootstrap.min.js"></script>

	<!-- Plugin For Google Maps -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="../assets/js/material-kit.js" type="text/javascript"></script>
```

Now in the `material-kit.js` you need to call all the functions from the $(document).ready(function({..}) to make sure all the initializations are done right. And you also should make sure that the objects like **materialKit** and **materialKitDemo** are available in your javascript.

Please let us know how you added the kit in your project and also please share a link with us or the folder structure in a private bitbucket.com repo so we can have a look and give you feedback.

Keep in touch,
Alex

**Comment by mullojo** [comment]
Hi @alexandru-paduraru I did get the templates working with Meteor now! 🎉

Some of the changes needed were pretty easy actually but they don't seem to work perfectly without me starting to build my own page from the template.html file, but I'll try to cover what I did to get it working.   The Meteor community is getting to be huge, so I'm sure more people would love it if the templates could be used right away with Meteor.

A tiny bit about Meteor to cover some background.  Meteor is a "full stack", so it has server side code &  client side code.  The templates are really designed to run on the "front end" or client side, so I've primarily tested on the client side.  So the HTML, CSS, & JavaScript on the client side is pretty easy to get working.  Meteor has some other methods of loading UI elements to the client side, like: 1) Blaze 2) React & 3) Angular.  Meteor started with the Blaze package & now the most popular package with Meteor is React, but you can run a Meteor app or website without using Blaze, React, or Angular. That's what the templates were deigned for, so that's the level of "working" that makes the most sense.

So here is what I did in Meteor:

1) Update the jQuery package because of a minor error with the `jquery.dropdown.js `

Meteor error message:

> Unable to resolve some modules:
> 
>   "jquery" in                                 
> /Users/me/testing_material_kit_2/client/assets/js/jquery.dropdown.js
> (web.browser)
>                                               
> If you notice problems related to these missing modules, consider running:
>                                               
>   meteor npm install --save jquery    

So I just ran the simple command: `meteor npm install --save jquery`. This fixed this error 💯 

No the only thing that really has to be done it to remove a couple HTML tags from the HTML files.  Because Meteor is awesome & had some built in intelligence, it only expects to see `<body>`, `<head>`, and `<template>`tags at the top level by default, so I just deleted the following lines in an HTML template:

`<!doctype html>`
`<html lang="en">`

`</html>`

Meteor builds these tags in each HTML document by default.  An error message clearly tells you to remove them.

The last thing you need to do then is move the JavaScript dependency links at the bottom of each HTML template page inside the `</body>` ending tag.

Save the whole file structure for Creative Kit Pro in the "client" directory inside your Meteor project directory and you have a working site! 🥇 

Let me know if you want more details. I build the 1st 1/3 of my site in a couple hours after making this fix, so the templates are awesome! Saving me tons of time.  I really appreciate the work in great coding & design.  Nice polish!

**Comment by mullojo** [comment]
Hi @alexandru-paduraru , I'm wondering if you have or know of customers who have used Media Kit Pro to make an email template?  Do you have any knowledge on that topic?  Many Thanks!
