### ISSUE TITLE
Missing cards

### ISSUE THREAD

**Issue by mentorgh** [timcreative/material-kit#6]
Where are the cards? Main component of material kit probably :'(

**Comment by waghcwb** [comment]
Check this file `assets/sass/material-kit/_cards.scss`.

You can create cards with this
```
<div class="card">
	<div class="card-image">
		<img class="card-img-top" src="img/bg3.jpeg">
		<h5 class="card-image-headline">Heading</h5>
	</div>
	<div class="card-body">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae vel, saepe illo amet, dolore minus. Quia placeat, quam, sunt et iste iure cumque harum, perferendis facilis nam temporibus itaque cupiditate.
	</div>
	<div class="card-footer">
		footer
	</div>
</div>
```

Take a look at the result
![image](https://cloud.githubusercontent.com/assets/6169950/14478976/bdb4d85e-00f0-11e6-8366-80bfb155f042.png)

**Comment by alexandru-paduraru** [comment]
@mentorgh thank you for pointing out. We didn't add them in our documentation because we didn't redesigned them. So they are there but they come with the default style that @waghcwb presented. Hope you can use them like that till we will make them have a better look and officially present them in the presentation page and in documentation.

Best,
Alex
